// source: grpc-models/chatbot.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.basic_grpc_service.AnswerType', null, global);
goog.exportSymbol('proto.basic_grpc_service.ChatHistoryEntry', null, global);
goog.exportSymbol('proto.basic_grpc_service.ChatHistoryEntry.ResponseType', null, global);
goog.exportSymbol('proto.basic_grpc_service.ChatReply', null, global);
goog.exportSymbol('proto.basic_grpc_service.ChatRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.basic_grpc_service.ChatRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.basic_grpc_service.ChatRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.basic_grpc_service.ChatRequest.displayName = 'proto.basic_grpc_service.ChatRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.basic_grpc_service.ChatReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.basic_grpc_service.ChatReply.repeatedFields_, null);
};
goog.inherits(proto.basic_grpc_service.ChatReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.basic_grpc_service.ChatReply.displayName = 'proto.basic_grpc_service.ChatReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.basic_grpc_service.ChatHistoryEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.basic_grpc_service.ChatHistoryEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.basic_grpc_service.ChatHistoryEntry.displayName = 'proto.basic_grpc_service.ChatHistoryEntry';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.basic_grpc_service.ChatRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.basic_grpc_service.ChatRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.basic_grpc_service.ChatRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = msg.getName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    message: (f = msg.getMessage()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    requestStartTime: (f = msg.getRequestStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.basic_grpc_service.ChatRequest}
 */
proto.basic_grpc_service.ChatRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.basic_grpc_service.ChatRequest;
  return proto.basic_grpc_service.ChatRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.basic_grpc_service.ChatRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.basic_grpc_service.ChatRequest}
 */
proto.basic_grpc_service.ChatRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRequestStartTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.basic_grpc_service.ChatRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.basic_grpc_service.ChatRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.basic_grpc_service.ChatRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getRequestStartTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue name = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.basic_grpc_service.ChatRequest.prototype.getName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
*/
proto.basic_grpc_service.ChatRequest.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
 */
proto.basic_grpc_service.ChatRequest.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatRequest.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue message = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.basic_grpc_service.ChatRequest.prototype.getMessage = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
*/
proto.basic_grpc_service.ChatRequest.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
 */
proto.basic_grpc_service.ChatRequest.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatRequest.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp request_start_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.basic_grpc_service.ChatRequest.prototype.getRequestStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
*/
proto.basic_grpc_service.ChatRequest.prototype.setRequestStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatRequest} returns this
 */
proto.basic_grpc_service.ChatRequest.prototype.clearRequestStartTime = function() {
  return this.setRequestStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatRequest.prototype.hasRequestStartTime = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.basic_grpc_service.ChatReply.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.basic_grpc_service.ChatReply.prototype.toObject = function(opt_includeInstance) {
  return proto.basic_grpc_service.ChatReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.basic_grpc_service.ChatReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: (f = msg.getMessage()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    answerFound: (f = msg.getAnswerFound()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    replyInBytes: (f = msg.getReplyInBytes()) && google_protobuf_wrappers_pb.BytesValue.toObject(includeInstance, f),
    messageSizeInBytes: (f = msg.getMessageSizeInBytes()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    messageSizeInMegabytes: (f = msg.getMessageSizeInMegabytes()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    requestReceivedTime: (f = msg.getRequestReceivedTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    requestProcessedDuration: (f = msg.getRequestProcessedDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    dynamicPayload: (f = msg.getDynamicPayload()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    packedNumbersList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    optionalField: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.basic_grpc_service.ChatReply}
 */
proto.basic_grpc_service.ChatReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.basic_grpc_service.ChatReply;
  return proto.basic_grpc_service.ChatReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.basic_grpc_service.ChatReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.basic_grpc_service.ChatReply}
 */
proto.basic_grpc_service.ChatReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setAnswerFound(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.BytesValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BytesValue.deserializeBinaryFromReader);
      msg.setReplyInBytes(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setMessageSizeInBytes(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setMessageSizeInMegabytes(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRequestReceivedTime(value);
      break;
    case 7:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRequestProcessedDuration(value);
      break;
    case 8:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setDynamicPayload(value);
      break;
    case 9:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPackedNumbers(values[i]);
      }
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOptionalField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.basic_grpc_service.ChatReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.basic_grpc_service.ChatReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.basic_grpc_service.ChatReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAnswerFound();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getReplyInBytes();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.BytesValue.serializeBinaryToWriter
    );
  }
  f = message.getMessageSizeInBytes();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getMessageSizeInMegabytes();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getRequestReceivedTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRequestProcessedDuration();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getDynamicPayload();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getPackedNumbersList();
  if (f.length > 0) {
    writer.writePackedInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt32(
      10,
      f
    );
  }
};


/**
 * optional google.protobuf.StringValue message = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.basic_grpc_service.ChatReply.prototype.getMessage = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue answer_found = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.basic_grpc_service.ChatReply.prototype.getAnswerFound = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setAnswerFound = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearAnswerFound = function() {
  return this.setAnswerFound(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasAnswerFound = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.BytesValue reply_in_bytes = 3;
 * @return {?proto.google.protobuf.BytesValue}
 */
proto.basic_grpc_service.ChatReply.prototype.getReplyInBytes = function() {
  return /** @type{?proto.google.protobuf.BytesValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BytesValue, 3));
};


/**
 * @param {?proto.google.protobuf.BytesValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setReplyInBytes = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearReplyInBytes = function() {
  return this.setReplyInBytes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasReplyInBytes = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Int32Value message_size_in_bytes = 4;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.basic_grpc_service.ChatReply.prototype.getMessageSizeInBytes = function() {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 4));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setMessageSizeInBytes = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearMessageSizeInBytes = function() {
  return this.setMessageSizeInBytes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasMessageSizeInBytes = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue message_size_in_megabytes = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.basic_grpc_service.ChatReply.prototype.getMessageSizeInMegabytes = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setMessageSizeInMegabytes = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearMessageSizeInMegabytes = function() {
  return this.setMessageSizeInMegabytes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasMessageSizeInMegabytes = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp request_received_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.basic_grpc_service.ChatReply.prototype.getRequestReceivedTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setRequestReceivedTime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearRequestReceivedTime = function() {
  return this.setRequestReceivedTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasRequestReceivedTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Duration request_processed_duration = 7;
 * @return {?proto.google.protobuf.Duration}
 */
proto.basic_grpc_service.ChatReply.prototype.getRequestProcessedDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 7));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setRequestProcessedDuration = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearRequestProcessedDuration = function() {
  return this.setRequestProcessedDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasRequestProcessedDuration = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Any dynamic_payload = 8;
 * @return {?proto.google.protobuf.Any}
 */
proto.basic_grpc_service.ChatReply.prototype.getDynamicPayload = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 8));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
*/
proto.basic_grpc_service.ChatReply.prototype.setDynamicPayload = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearDynamicPayload = function() {
  return this.setDynamicPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasDynamicPayload = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated int32 packed_numbers = 9;
 * @return {!Array<number>}
 */
proto.basic_grpc_service.ChatReply.prototype.getPackedNumbersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.setPackedNumbersList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.addPackedNumbers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearPackedNumbersList = function() {
  return this.setPackedNumbersList([]);
};


/**
 * optional int32 optional_field = 10;
 * @return {number}
 */
proto.basic_grpc_service.ChatReply.prototype.getOptionalField = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.setOptionalField = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.basic_grpc_service.ChatReply} returns this
 */
proto.basic_grpc_service.ChatReply.prototype.clearOptionalField = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.basic_grpc_service.ChatReply.prototype.hasOptionalField = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.basic_grpc_service.ChatHistoryEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.basic_grpc_service.ChatHistoryEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatHistoryEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestMessage: jspb.Message.getFieldWithDefault(msg, 1, ""),
    responseMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.basic_grpc_service.ChatHistoryEntry}
 */
proto.basic_grpc_service.ChatHistoryEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.basic_grpc_service.ChatHistoryEntry;
  return proto.basic_grpc_service.ChatHistoryEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.basic_grpc_service.ChatHistoryEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.basic_grpc_service.ChatHistoryEntry}
 */
proto.basic_grpc_service.ChatHistoryEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponseMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.basic_grpc_service.ChatHistoryEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.basic_grpc_service.ChatHistoryEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.basic_grpc_service.ChatHistoryEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResponseMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.basic_grpc_service.ChatHistoryEntry.ResponseType = {
  UNKNOWN: 0,
  HELP: 1,
  GREETING: 2
};

/**
 * optional string request_message = 1;
 * @return {string}
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.getRequestMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.basic_grpc_service.ChatHistoryEntry} returns this
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.setRequestMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string response_message = 2;
 * @return {string}
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.getResponseMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.basic_grpc_service.ChatHistoryEntry} returns this
 */
proto.basic_grpc_service.ChatHistoryEntry.prototype.setResponseMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.basic_grpc_service.AnswerType = {
  UNKNOWN: 0,
  HELP: 1,
  GREETING: 2
};

goog.object.extend(exports, proto.basic_grpc_service);
